
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Cfg.Battle
{ 
    /// <summary>
    /// 战斗属性
    /// </summary>
    public enum CombatType
    {
        /// <summary>
        /// 物理
        /// </summary>
        Physical = 0,
        /// <summary>
        /// 火
        /// </summary>
        Fire = 1,
        /// <summary>
        /// 冰
        /// </summary>
        Ice = 2,
        /// <summary>
        /// 雷
        /// </summary>
        Lightning = 3,
        /// <summary>
        /// 风
        /// </summary>
        Wind = 4,
        /// <summary>
        /// 量子
        /// </summary>
        Quantum = 5,
        /// <summary>
        /// 虚数
        /// </summary>
        Imaginary = 6,
    }

} 

