
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Cysharp.Threading.Tasks;

namespace Game.Cfg
{
public partial class ConfigService
{
    public Battle.TbBattleSettings TbBattleSettings {get; private set; }
    public Unit.TbUnitData TbUnitData {get; private set; }

    public async UniTask LoadAll(System.Func<string, UniTask<ByteBuf>> loader)
    {
        var tasks = new UniTask[]
        {      
            UniTask.Create(async () => TbBattleSettings = new Battle.TbBattleSettings(await loader("battle_tbbattlesettings"))),
            UniTask.Create(async () => TbUnitData = new Unit.TbUnitData(await loader("unit_tbunitdata"))),
        };
        await UniTask.WhenAll(tasks);
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBattleSettings.ResolveRef(this);
        TbUnitData.ResolveRef(this);
    }
}

}
