
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Cfg
{ 
    /// <summary>
    /// 数值类型
    /// </summary>
    public enum NumericId
    {
        /// <summary>
        /// 生命值
        /// </summary>
        HP = 1,
        /// <summary>
        /// 能量值
        /// </summary>
        Energy = 2,
        /// <summary>
        /// 生命上限
        /// </summary>
        MaxHP = 1001,
        /// <summary>
        /// 移动速度
        /// </summary>
        MoveSPD = 1003,
        /// <summary>
        /// 防御力
        /// </summary>
        DEF = 1004,
        /// <summary>
        /// 攻击力
        /// </summary>
        ATK = 1005,
        /// <summary>
        /// 行动间隔
        /// </summary>
        ACTITV = 2001,
        /// <summary>
        /// 行动速度
        /// </summary>
        ACTSPD = 2002,
        /// <summary>
        /// 嘲讽值
        /// </summary>
        Taunt = 2003,
        /// <summary>
        /// 暴击率
        /// </summary>
        CritRate = 2004,
        /// <summary>
        /// 暴击伤害
        /// </summary>
        CritDMG = 2005,
        /// <summary>
        /// 击破特攻
        /// </summary>
        BreakEffect = 2006,
        /// <summary>
        /// 治疗量加成
        /// </summary>
        OutgoingHealingBoost = 2007,
        /// <summary>
        /// 能量上限
        /// </summary>
        MaxEnergy = 2008,
        /// <summary>
        /// 能量恢复效率
        /// </summary>
        EnergyRegenerationRate = 2009,
        /// <summary>
        /// 效果命中
        /// </summary>
        EffectHitRate = 2010,
        /// <summary>
        /// 效果抵抗
        /// </summary>
        EffectRES = 2011,
        /// <summary>
        /// 物理属性伤害提高
        /// </summary>
        PhysicalDMGBoost = 3001,
        /// <summary>
        /// 火属性伤害提高
        /// </summary>
        FireDMGBoost = 3002,
        /// <summary>
        /// 冰属性伤害提高
        /// </summary>
        IceDMGBoost = 3003,
        /// <summary>
        /// 雷属性伤害提高
        /// </summary>
        LightningDMGBoost = 3004,
        /// <summary>
        /// 风属性伤害提高
        /// </summary>
        WindDMGBoost = 3005,
        /// <summary>
        /// 量子属性伤害提高
        /// </summary>
        QuantumDMGBoost = 3006,
        /// <summary>
        /// 虚数属性伤害提高
        /// </summary>
        ImaginaryDMGBoost = 3007,
        /// <summary>
        /// 物理属性抗性提高
        /// </summary>
        PhysicalRESBoost = 3008,
        /// <summary>
        /// 火属性抗性提高
        /// </summary>
        FireRESBoost = 3009,
        /// <summary>
        /// 冰属性抗性提高
        /// </summary>
        IceRESBoost = 3010,
        /// <summary>
        /// 雷属性抗性提高
        /// </summary>
        LightningRESBoost = 3011,
        /// <summary>
        /// 风属性抗性提高
        /// </summary>
        WindRESBoost = 3012,
        /// <summary>
        /// 量子属性抗性提高
        /// </summary>
        QuantumRESBoost = 3013,
        /// <summary>
        /// 虚数属性抗性提高
        /// </summary>
        ImaginaryRESBoost = 3014,
    }

} 

