
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Cfg
{ 
    /// <summary>
    /// 数值类型
    /// </summary>
    public enum NumericId
    {
        /// <summary>
        /// 生命值
        /// </summary>
        Hp = 0,
        /// <summary>
        /// 生命上限
        /// </summary>
        HpMax = 1,
        /// <summary>
        /// 魔力值
        /// </summary>
        Mp = 2,
        /// <summary>
        /// 魔力上限
        /// </summary>
        MpMax = 3,
        /// <summary>
        /// 速度
        /// </summary>
        Speed = 4,
        /// <summary>
        /// 防御
        /// </summary>
        Defense = 5,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalRate = 6,
        /// <summary>
        /// 暴击伤害
        /// </summary>
        CriticalDamage = 7,
        /// <summary>
        /// 攻击力
        /// </summary>
        Attack = 8,
        /// <summary>
        /// 攻击距离
        /// </summary>
        AttackRange = 9,
        /// <summary>
        /// 攻击间隔
        /// </summary>
        AttackInterval = 10,
        /// <summary>
        /// 攻击速度
        /// </summary>
        AttackSpeed = 11,
    }

} 

