
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Cfg
{
public sealed partial class UnitData : Luban.BeanBase
{
    public UnitData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        ModelPath = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AttributesX1000 = new System.Collections.Generic.List<Unit.UnitAttrData>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Unit.UnitAttrData _e0;  _e0 = Unit.UnitAttrData.DeserializeUnitAttrData(_buf); AttributesX1000.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SkillIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SkillIds.Add(_e0);}}
    }

    public static UnitData DeserializeUnitData(ByteBuf _buf)
    {
        return new UnitData(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 模型路径
    /// </summary>
    public readonly string ModelPath;
    public readonly System.Collections.Generic.List<Unit.UnitAttrData> AttributesX1000;
    public readonly System.Collections.Generic.List<int> SkillIds;
   
    public const int __ID__ = -228507794;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigService tables)
    {
        
        
        
        
        foreach (var _e in AttributesX1000) { _e?.ResolveRef(tables); }
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "modelPath:" + ModelPath + ","
        + "attributesX1000:" + Luban.StringUtil.CollectionToString(AttributesX1000) + ","
        + "skillIds:" + Luban.StringUtil.CollectionToString(SkillIds) + ","
        + "}";
    }
}

}
