
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Cfg
{
public sealed partial class UnitData : Luban.BeanBase
{
    public UnitData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        ModelPath = _buf.ReadString();
        ControllerName = _buf.ReadString();
        RadiusX1000 = _buf.ReadLong();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BaseStatsX1000 = new System.Collections.Generic.Dictionary<NumericId, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericId _k0;  _k0 = (NumericId)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     BaseStatsX1000.Add(_k0, _v0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);LevelGrowthStatsX1000 = new System.Collections.Generic.Dictionary<NumericId, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericId _k0;  _k0 = (NumericId)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     LevelGrowthStatsX1000.Add(_k0, _v0);}}
    }

    public static UnitData DeserializeUnitData(ByteBuf _buf)
    {
        return new UnitData(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string Desc;
    public readonly string ModelPath;
    public readonly string ControllerName;
    public readonly long RadiusX1000;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<NumericId, long> BaseStatsX1000;
    /// <summary>
    /// 成长属性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<NumericId, long> LevelGrowthStatsX1000;
   
    public const int __ID__ = -228507794;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigService tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "modelPath:" + ModelPath + ","
        + "controllerName:" + ControllerName + ","
        + "radiusX1000:" + RadiusX1000 + ","
        + "baseStatsX1000:" + Luban.StringUtil.CollectionToString(BaseStatsX1000) + ","
        + "levelGrowthStatsX1000:" + Luban.StringUtil.CollectionToString(LevelGrowthStatsX1000) + ","
        + "}";
    }
}

}
