
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Cfg.Unit
{
public sealed partial class UnitAttrData : Luban.BeanBase
{
    public UnitAttrData(ByteBuf _buf) 
    {
        BaseValue = _buf.ReadLong();
        GrowValue = _buf.ReadLong();
    }

    public static UnitAttrData DeserializeUnitAttrData(ByteBuf _buf)
    {
        return new Unit.UnitAttrData(_buf);
    }

    /// <summary>
    /// 基础值
    /// </summary>
    public readonly long BaseValue;
    /// <summary>
    /// 成长值
    /// </summary>
    public readonly long GrowValue;
   
    public const int __ID__ = -765996279;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigService tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "baseValue:" + BaseValue + ","
        + "growValue:" + GrowValue + ","
        + "}";
    }
}

}
