
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace GameEditor.ConfigEditor.Model.Avg
{

public sealed class NormalBehaviour :  Avg.DialogueBehaviour 
{
    public NormalBehaviour()
    {
            target = GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget.Opener2Owner;
            avgResults = new System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Result.ResultParam>();
            nexts = new System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Avg.Next>();
    }
    public override string GetTypeStr() => TYPE_STR;
    private const string TYPE_STR = "NormalBehaviour";

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["target"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { target = (GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget)System.Enum.Parse(typeof(GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget), _fieldJson); } else if(_fieldJson.IsNumber) { target = (GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
            else
            {
                target = GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget.Opener2Owner;
            }
        }
        
        { 
            var _fieldJson = _json["avg_results"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } avgResults = new System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Result.ResultParam>(); foreach(SimpleJSON.JSONNode __e0 in _fieldJson.Children) { GameEditor.ConfigEditor.Model.Result.ResultParam __v0;  
                if (!__e0.IsObject)
                {
                    throw new SerializationException();
                }
                __v0 = GameEditor.ConfigEditor.Model.Result.ResultParam.LoadJsonResultParam(__e0);  avgResults.Add(__v0); }  
            }
            else
            {
                avgResults = new System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Result.ResultParam>();
            }
        }
        
        { 
            var _fieldJson = _json["nexts"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } nexts = new System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Avg.Next>(); foreach(SimpleJSON.JSONNode __e0 in _fieldJson.Children) { GameEditor.ConfigEditor.Model.Avg.Next __v0;  if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = GameEditor.ConfigEditor.Model.Avg.Next.LoadJsonNext(__e0);  nexts.Add(__v0); }  
            }
            else
            {
                nexts = new System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Avg.Next>();
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["target"] = new JSONNumber((int)target);
        }

        if (avgResults != null)
        {
            { var __cjson0 = new JSONArray(); foreach(var __e0 in avgResults) { { var __bjson = new JSONObject();  GameEditor.ConfigEditor.Model.Result.ResultParam.SaveJsonResultParam(__e0, __bjson); __cjson0["null"] = __bjson; } } __cjson0.Inline = __cjson0.Count == 0; _json["avg_results"] = __cjson0; }
        }

        if (nexts != null)
        {
            { var __cjson0 = new JSONArray(); foreach(var __e0 in nexts) { { var __bjson = new JSONObject();  GameEditor.ConfigEditor.Model.Avg.Next.SaveJsonNext(__e0, __bjson); __cjson0["null"] = __bjson; } } __cjson0.Inline = __cjson0.Count == 0; _json["nexts"] = __cjson0; }
        }
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderNormalBehaviour(NormalBehaviour obj)
    {
        obj.Render();
    }

    public override void Render()
    {
{
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("目标类型", "target"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("target", "目标类型"), GUILayout.Width(100));
}
{
    if (ConfigEditorSettings.showComment)
    {
        var __index1 = (int)this.target;
        var __alias1 = (Avg.AvgDetermineTarget_Alias)this.target;
        __alias1 = (Avg.AvgDetermineTarget_Alias)UnityEditor.EditorGUILayout.EnumPopup(__alias1, GUILayout.Width(150));
        var __item1 = Avg.AvgDetermineTarget_Metadata.GetByNameOrAlias(__alias1.ToString());
        this.target = (GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget)__item1.Value;
    }
    else
    {
        this.target = (GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget)UnityEditor.EditorGUILayout.EnumPopup(this.target, GUILayout.Width(150));
    }
}
UnityEditor.EditorGUILayout.EndHorizontal();UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("Results", "avg_results"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("avg_results", "Results"), GUILayout.Width(100));
}
{
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);
    int __n1 = this.avgResults.Count;
    UnityEditor.EditorGUILayout.LabelField("长度: " + __n1.ToString());
    for (int __i1 = 0; __i1 < __n1; __i1++)
    {
        UnityEditor.EditorGUILayout.BeginHorizontal();
        if (GUILayout.Button("-", GUILayout.Width(20)))
        {
            this.avgResults.RemoveAt(__i1);
            UnityEditor.EditorGUILayout.EndHorizontal();
            break;
        }
        UnityEditor.EditorGUILayout.LabelField(__i1.ToString(), GUILayout.Width(20));
        GameEditor.ConfigEditor.Model.Result.ResultParam __e1 = this.avgResults[__i1];
        {
    if (__e1 == null)
{   
    __e1 = Result.ResultParam.Create("DifferDmg");
}
    Result.ResultParam.RenderResultParam(ref __e1);
};
        this.avgResults[__i1] = __e1;
        UnityEditor.EditorGUILayout.EndHorizontal();
    }
    UnityEditor.EditorGUILayout.BeginHorizontal();
    if (GUILayout.Button("+", GUILayout.Width(20)))
    {
        GameEditor.ConfigEditor.Model.Result.ResultParam __e1;
        __e1 = Result.ResultParam.Create("DifferDmg");;
        this.avgResults.Add(__e1);
    }
    if (ConfigEditorSettings.showImportButton && GUILayout.Button("import", GUILayout.Width(100)))
    {
        ConfigEditorImportWindow.Open((__importJsonText1) => 
        {
            var __importJson1 = SimpleJSON.JSON.Parse(__importJsonText1);
            GameEditor.ConfigEditor.Model.Result.ResultParam __importElement1;
            
if (!__importJson1.IsObject)
{
    throw new SerializationException();
}
__importElement1 = GameEditor.ConfigEditor.Model.Result.ResultParam.LoadJsonResultParam(__importJson1);
            this.avgResults.Add(__importElement1);
        });
    }
    UnityEditor.EditorGUILayout.EndHorizontal();
    UnityEditor.EditorGUILayout.EndVertical();
}
UnityEditor.EditorGUILayout.EndHorizontal();UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("下句候选列表", "nexts"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("nexts", "下句候选列表"), GUILayout.Width(100));
}
{
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);
    int __n1 = this.nexts.Count;
    UnityEditor.EditorGUILayout.LabelField("长度: " + __n1.ToString());
    for (int __i1 = 0; __i1 < __n1; __i1++)
    {
        UnityEditor.EditorGUILayout.BeginHorizontal();
        if (GUILayout.Button("-", GUILayout.Width(20)))
        {
            this.nexts.RemoveAt(__i1);
            UnityEditor.EditorGUILayout.EndHorizontal();
            break;
        }
        UnityEditor.EditorGUILayout.LabelField(__i1.ToString(), GUILayout.Width(20));
        GameEditor.ConfigEditor.Model.Avg.Next __e1 = this.nexts[__i1];
        {
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("下句id", "next_id"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("next_id", "下句id"), GUILayout.Width(100));
}
__e1.nextId = UnityEditor.EditorGUILayout.IntField(__e1.nextId, GUILayout.Width(150));
UnityEditor.EditorGUILayout.EndHorizontal();UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("下句条件", "next_condition"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("next_condition", "下句条件"), GUILayout.Width(100));
}
{
    if (__e1.nextCondition == null)
{   
    __e1.nextCondition = ConditionParam.Create("Always");
}
    ConditionParam.RenderConditionParam(ref __e1.nextCondition);
}
UnityEditor.EditorGUILayout.EndHorizontal();    UnityEditor.EditorGUILayout.EndVertical();
};
        this.nexts[__i1] = __e1;
        UnityEditor.EditorGUILayout.EndHorizontal();
    }
    UnityEditor.EditorGUILayout.BeginHorizontal();
    if (GUILayout.Button("+", GUILayout.Width(20)))
    {
        GameEditor.ConfigEditor.Model.Avg.Next __e1;
        __e1 = new Avg.Next();;
        this.nexts.Add(__e1);
    }
    if (ConfigEditorSettings.showImportButton && GUILayout.Button("import", GUILayout.Width(100)))
    {
        ConfigEditorImportWindow.Open((__importJsonText1) => 
        {
            var __importJson1 = SimpleJSON.JSON.Parse(__importJsonText1);
            GameEditor.ConfigEditor.Model.Avg.Next __importElement1;
            if(!__importJson1.IsObject) { throw new SerializationException(); }  __importElement1 = GameEditor.ConfigEditor.Model.Avg.Next.LoadJsonNext(__importJson1);
            this.nexts.Add(__importElement1);
        });
    }
    UnityEditor.EditorGUILayout.EndHorizontal();
    UnityEditor.EditorGUILayout.EndVertical();
}
UnityEditor.EditorGUILayout.EndHorizontal();    UnityEditor.EditorGUILayout.EndVertical();
}    }
    public static NormalBehaviour LoadJsonNormalBehaviour(SimpleJSON.JSONNode _json)
    {
        NormalBehaviour obj = new Avg.NormalBehaviour();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonNormalBehaviour(NormalBehaviour _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 目标类型
    /// </summary>
    public GameEditor.ConfigEditor.Model.Avg.AvgDetermineTarget target;
    /// <summary>
    /// Results
    /// </summary>
    public System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Result.ResultParam> avgResults;
    /// <summary>
    /// 下句候选列表
    /// </summary>
    public System.Collections.Generic.List<GameEditor.ConfigEditor.Model.Avg.Next> nexts;

    public override string ToString()
    {
        return "{ "
        + "target:" + target + ","
        + "avgResults:" + Luban.StringUtil.CollectionToString(avgResults) + ","
        + "nexts:" + Luban.StringUtil.CollectionToString(nexts) + ","
        + "}";
    }
}

}

