
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model.Story
{
    public enum StoryType
    {
        /// <summary>
        /// 挑战
        /// </summary>
        Challenge = 0,
        /// <summary>
        /// 战役
        /// </summary>
        Story = 1,
    }

    public enum StoryType_Alias
    {
        挑战 = 0,
        战役 = 1,
    }

    public static class StoryType_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Challenge = new Luban.EditorEnumItemInfo("Challenge", "挑战", 0, "挑战");
        public static readonly Luban.EditorEnumItemInfo Story = new Luban.EditorEnumItemInfo("Story", "战役", 1, "战役");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Challenge,
            Story,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

