
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model.Counter
{
    public enum CounterName
    {
        /// <summary>
        /// 试做计数器1
        /// </summary>
        Counter1 = 0,
        /// <summary>
        /// 试做计数器2
        /// </summary>
        Counter2 = 1,
        /// <summary>
        /// 试做计数器3
        /// </summary>
        Counter3 = 2,
        /// <summary>
        /// 试做计数器4
        /// </summary>
        Counter4 = 3,
        /// <summary>
        /// 试做计数器5
        /// </summary>
        Counter5 = 4,
        /// <summary>
        /// 试做计数器6
        /// </summary>
        Counter6 = 5,
        /// <summary>
        /// 试做计数器7
        /// </summary>
        Counter7 = 6,
        /// <summary>
        /// 试做计数器8
        /// </summary>
        Counter8 = 7,
        /// <summary>
        /// 试做计数器9
        /// </summary>
        Counter9 = 8,
        /// <summary>
        /// 试做计数器10
        /// </summary>
        Counter10 = 9,
        /// <summary>
        /// 学习技能次数
        /// </summary>
        LearnSkillCounter = 10,
        /// <summary>
        /// 获取属性值次数
        /// </summary>
        GetPropertyCounter = 11,
        /// <summary>
        /// 获取骰子次数
        /// </summary>
        GetDiceCounter = 12,
    }

    public enum CounterName_Alias
    {
        试做计数器1 = 0,
        试做计数器2 = 1,
        试做计数器3 = 2,
        试做计数器4 = 3,
        试做计数器5 = 4,
        试做计数器6 = 5,
        试做计数器7 = 6,
        试做计数器8 = 7,
        试做计数器9 = 8,
        试做计数器10 = 9,
        学习技能次数 = 10,
        获取属性值次数 = 11,
        获取骰子次数 = 12,
    }

    public static class CounterName_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Counter1 = new Luban.EditorEnumItemInfo("Counter1", "试做计数器1", 0, "试做计数器1");
        public static readonly Luban.EditorEnumItemInfo Counter2 = new Luban.EditorEnumItemInfo("Counter2", "试做计数器2", 1, "试做计数器2");
        public static readonly Luban.EditorEnumItemInfo Counter3 = new Luban.EditorEnumItemInfo("Counter3", "试做计数器3", 2, "试做计数器3");
        public static readonly Luban.EditorEnumItemInfo Counter4 = new Luban.EditorEnumItemInfo("Counter4", "试做计数器4", 3, "试做计数器4");
        public static readonly Luban.EditorEnumItemInfo Counter5 = new Luban.EditorEnumItemInfo("Counter5", "试做计数器5", 4, "试做计数器5");
        public static readonly Luban.EditorEnumItemInfo Counter6 = new Luban.EditorEnumItemInfo("Counter6", "试做计数器6", 5, "试做计数器6");
        public static readonly Luban.EditorEnumItemInfo Counter7 = new Luban.EditorEnumItemInfo("Counter7", "试做计数器7", 6, "试做计数器7");
        public static readonly Luban.EditorEnumItemInfo Counter8 = new Luban.EditorEnumItemInfo("Counter8", "试做计数器8", 7, "试做计数器8");
        public static readonly Luban.EditorEnumItemInfo Counter9 = new Luban.EditorEnumItemInfo("Counter9", "试做计数器9", 8, "试做计数器9");
        public static readonly Luban.EditorEnumItemInfo Counter10 = new Luban.EditorEnumItemInfo("Counter10", "试做计数器10", 9, "试做计数器10");
        public static readonly Luban.EditorEnumItemInfo LearnSkillCounter = new Luban.EditorEnumItemInfo("LearnSkillCounter", "学习技能次数", 10, "学习技能次数");
        public static readonly Luban.EditorEnumItemInfo GetPropertyCounter = new Luban.EditorEnumItemInfo("GetPropertyCounter", "获取属性值次数", 11, "获取属性值次数");
        public static readonly Luban.EditorEnumItemInfo GetDiceCounter = new Luban.EditorEnumItemInfo("GetDiceCounter", "获取骰子次数", 12, "获取骰子次数");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Counter1,
            Counter2,
            Counter3,
            Counter4,
            Counter5,
            Counter6,
            Counter7,
            Counter8,
            Counter9,
            Counter10,
            LearnSkillCounter,
            GetPropertyCounter,
            GetDiceCounter,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

