
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace GameEditor.ConfigEditor.Model.BattleAIPickTarget
{

public abstract class PickTargetParam :  Luban.EditorBeanBase 
{
    public PickTargetParam()
    {
    }
    public abstract string GetTypeStr();

    private int _typeIndex = -1;
    private int TypeIndex => _typeIndex;
    private static string[] Types = new string[]
    {
        "SkillAoe",
        "SortDice",
        "SortProperty",
    };
    private static string[] TypeAlias = new string[]
    {
        "技能AOE",
        "骰子排列",
        "属性排列",
    };

    public static PickTargetParam Create(string type)
    {
        switch (type)
        {
            case "BattleAIPickTarget.SkillAoe":   
            case "SkillAoe":
            {
                var obj = new BattleAIPickTarget.SkillAoe();
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "BattleAIPickTarget.SortDice":   
            case "SortDice":
            {
                var obj = new BattleAIPickTarget.SortDice();
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "BattleAIPickTarget.SortProperty":   
            case "SortProperty":
            {
                var obj = new BattleAIPickTarget.SortProperty();
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            default: return null;
        }
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderPickTargetParam(ref PickTargetParam obj)
    {
        UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);
        var array = ConfigEditorSettings.showComment ? TypeAlias : Types;
        UnityEditor.EditorGUILayout.BeginHorizontal();
        UnityEditor.EditorGUILayout.LabelField("类型", GUILayout.Width(100));
        var index = UnityEditor.EditorGUILayout.Popup(obj.TypeIndex, array, GUILayout.Width(200));
        if (obj.TypeIndex != index)
        {
            obj = Create(Types[index]);
        }
        UnityEditor.EditorGUILayout.EndHorizontal();
        obj?.Render();
        UnityEditor.EditorGUILayout.EndVertical();
    }

    public override void Render()
    {
    }
    public static PickTargetParam LoadJsonPickTargetParam(SimpleJSON.JSONNode _json)
    {
        string type = _json["$type"];
        PickTargetParam obj;
        switch (type)
        {
            case "BattleAIPickTarget.SkillAoe":   
            case "SkillAoe":
            {
                obj = new BattleAIPickTarget.SkillAoe(); 
                obj._typeIndex = Array.IndexOf(Types, "SkillAoe");
                break;
            }
            case "BattleAIPickTarget.SortDice":   
            case "SortDice":
            {
                obj = new BattleAIPickTarget.SortDice(); 
                obj._typeIndex = Array.IndexOf(Types, "SortDice");
                break;
            }
            case "BattleAIPickTarget.SortProperty":   
            case "SortProperty":
            {
                obj = new BattleAIPickTarget.SortProperty(); 
                obj._typeIndex = Array.IndexOf(Types, "SortProperty");
                break;
            }
            default: throw new SerializationException();
        }
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonPickTargetParam(PickTargetParam _obj, SimpleJSON.JSONNode _json)
    {
        _json["$type"] = _obj.GetTypeStr();
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }


    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

