
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace GameEditor.ConfigEditor.Model.BattleAIPickTarget
{

public sealed class SkillAoe :  BattleAIPickTarget.PickTargetParam 
{
    public SkillAoe()
    {
    }
    public override string GetTypeStr() => TYPE_STR;
    private const string TYPE_STR = "SkillAoe";

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderSkillAoe(SkillAoe obj)
    {
        obj.Render();
    }

    public override void Render()
    {
    }
    public static SkillAoe LoadJsonSkillAoe(SimpleJSON.JSONNode _json)
    {
        SkillAoe obj = new BattleAIPickTarget.SkillAoe();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonSkillAoe(SkillAoe _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }


    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

