
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace GameEditor.ConfigEditor.Model.Enemy.Feature
{

/// <summary>
/// 不可被技能选中
/// </summary>
public sealed class BuildingFeature :  Enemy.Feature.EnemyFeature 
{
    public BuildingFeature()
    {
    }
    public override string GetTypeStr() => TYPE_STR;
    private const string TYPE_STR = "BuildingFeature";

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderBuildingFeature(BuildingFeature obj)
    {
        obj.Render();
    }

    public override void Render()
    {
    }
    public static BuildingFeature LoadJsonBuildingFeature(SimpleJSON.JSONNode _json)
    {
        BuildingFeature obj = new Enemy.Feature.BuildingFeature();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonBuildingFeature(BuildingFeature _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }


    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

