
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace GameEditor.ConfigEditor.Model
{

public sealed class AiArg :  Luban.EditorBeanBase 
{
    public AiArg()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["skill_id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  skillId = _fieldJson;
            }
            else
            {
                skillId = 0;
            }
        }
        
        { 
            var _fieldJson = _json["target_param"];
            if (_fieldJson != null)
            {
                
                if (!_fieldJson.IsObject)
                {
                    throw new SerializationException();
                }
                targetParam = GameEditor.ConfigEditor.Model.BattleAIPickTarget.PickTargetParam.LoadJsonPickTargetParam(_fieldJson);
            }
            else
            {
                targetParam = BattleAIPickTarget.PickTargetParam.Create("SkillAoe");
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["skill_id"] = new JSONNumber(skillId);
        }

        if (targetParam != null)
        {
            { var __bjson = new JSONObject();  GameEditor.ConfigEditor.Model.BattleAIPickTarget.PickTargetParam.SaveJsonPickTargetParam(targetParam, __bjson); _json["target_param"] = __bjson; }
        }
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderAiArg(AiArg obj)
    {
        obj.Render();
    }

    public override void Render()
    {
{
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("技能id", "skill_id"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("skill_id", "技能id"), GUILayout.Width(100));
}
this.skillId = UnityEditor.EditorGUILayout.IntField(this.skillId, GUILayout.Width(150));
UnityEditor.EditorGUILayout.EndHorizontal();UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("AI索敌参数", "target_param"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("target_param", "AI索敌参数"), GUILayout.Width(100));
}
{
    if (this.targetParam == null)
{   
    this.targetParam = BattleAIPickTarget.PickTargetParam.Create("SkillAoe");
}
    BattleAIPickTarget.PickTargetParam.RenderPickTargetParam(ref this.targetParam);
}
UnityEditor.EditorGUILayout.EndHorizontal();    UnityEditor.EditorGUILayout.EndVertical();
}    }
    public static AiArg LoadJsonAiArg(SimpleJSON.JSONNode _json)
    {
        AiArg obj = new AiArg();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonAiArg(AiArg _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public int skillId;
    /// <summary>
    /// AI索敌参数
    /// </summary>
    public GameEditor.ConfigEditor.Model.BattleAIPickTarget.PickTargetParam targetParam;

    public override string ToString()
    {
        return "{ "
        + "skillId:" + skillId + ","
        + "targetParam:" + targetParam + ","
        + "}";
    }
}

}

