
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model
{
    public enum BuffDecayPattern
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 减少1
        /// </summary>
        MinusOne = 1,
        /// <summary>
        /// 减半
        /// </summary>
        Half = 2,
    }

    public enum BuffDecayPattern_Alias
    {
        无 = 0,
        减少1 = 1,
        减半 = 2,
    }

    public static class BuffDecayPattern_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo None = new Luban.EditorEnumItemInfo("None", "无", 0, "无");
        public static readonly Luban.EditorEnumItemInfo MinusOne = new Luban.EditorEnumItemInfo("MinusOne", "减少1", 1, "减少1");
        public static readonly Luban.EditorEnumItemInfo Half = new Luban.EditorEnumItemInfo("Half", "减半", 2, "减半");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            None,
            MinusOne,
            Half,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

