
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model
{
    /// <summary>
    /// Buff生命周期
    /// </summary>
    public enum BuffLifeCycle
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 直到buff拥有者回合结束
        /// </summary>
        OwnerTurnEnd = 1,
        /// <summary>
        /// 直到buff拥有者的敌方回合结束
        /// </summary>
        OppositeTurnEnd = 2,
        /// <summary>
        /// 直到战斗结束
        /// </summary>
        BattleFinish = 3,
        /// <summary>
        /// 直到离开房间
        /// </summary>
        RoomLeave = 4,
        /// <summary>
        /// 直到离开楼层
        /// </summary>
        FloorLeave = 5,
    }

    public enum BuffLifeCycle_Alias
    {
        无 = 0,
        直到buff拥有者回合结束 = 1,
        直到buff拥有者的敌方回合结束 = 2,
        直到战斗结束 = 3,
        直到离开房间 = 4,
        直到离开楼层 = 5,
    }

    public static class BuffLifeCycle_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo None = new Luban.EditorEnumItemInfo("None", "无", 0, "无");
        public static readonly Luban.EditorEnumItemInfo OwnerTurnEnd = new Luban.EditorEnumItemInfo("OwnerTurnEnd", "直到buff拥有者回合结束", 1, "直到buff拥有者回合结束");
        public static readonly Luban.EditorEnumItemInfo OppositeTurnEnd = new Luban.EditorEnumItemInfo("OppositeTurnEnd", "直到buff拥有者的敌方回合结束", 2, "直到buff拥有者的敌方回合结束");
        public static readonly Luban.EditorEnumItemInfo BattleFinish = new Luban.EditorEnumItemInfo("BattleFinish", "直到战斗结束", 3, "直到战斗结束");
        public static readonly Luban.EditorEnumItemInfo RoomLeave = new Luban.EditorEnumItemInfo("RoomLeave", "直到离开房间", 4, "直到离开房间");
        public static readonly Luban.EditorEnumItemInfo FloorLeave = new Luban.EditorEnumItemInfo("FloorLeave", "直到离开楼层", 5, "直到离开楼层");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            None,
            OwnerTurnEnd,
            OppositeTurnEnd,
            BattleFinish,
            RoomLeave,
            FloorLeave,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

