
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model
{
    /// <summary>
    /// 角色的Tag
    /// </summary>
    public enum CharaTag
    {
        /// <summary>
        /// 人类
        /// </summary>
        Human = 0,
        /// <summary>
        /// 机械
        /// </summary>
        Machine = 1,
        /// <summary>
        /// 恶魔
        /// </summary>
        Demon = 2,
    }

    public enum CharaTag_Alias
    {
        人类 = 0,
        机械 = 1,
        恶魔 = 2,
    }

    public static class CharaTag_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Human = new Luban.EditorEnumItemInfo("Human", "人类", 0, "人类");
        public static readonly Luban.EditorEnumItemInfo Machine = new Luban.EditorEnumItemInfo("Machine", "机械", 1, "机械");
        public static readonly Luban.EditorEnumItemInfo Demon = new Luban.EditorEnumItemInfo("Demon", "恶魔", 2, "恶魔");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Human,
            Machine,
            Demon,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

