
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model
{
    /// <summary>
    /// 物品的大类
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 无种类
        /// </summary>
        NoType = 0,
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 1,
        /// <summary>
        /// 剑
        /// </summary>
        Sword = 2,
        /// <summary>
        /// 枪械
        /// </summary>
        Gun = 3,
        /// <summary>
        /// 护甲
        /// </summary>
        Armor = 4,
        /// <summary>
        /// 鞋子
        /// </summary>
        Shoes = 5,
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 6,
        /// <summary>
        /// 饰品
        /// </summary>
        Jewelry = 7,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 8,
        /// <summary>
        /// 药水
        /// </summary>
        Potion = 9,
        /// <summary>
        /// 人物技能
        /// </summary>
        CharaSkill = 10,
    }

    public enum ItemType_Alias
    {
        无种类 = 0,
        装备 = 1,
        剑 = 2,
        枪械 = 3,
        护甲 = 4,
        鞋子 = 5,
        头盔 = 6,
        饰品 = 7,
        消耗品 = 8,
        药水 = 9,
        人物技能 = 10,
    }

    public static class ItemType_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo NoType = new Luban.EditorEnumItemInfo("NoType", "无种类", 0, "无种类");
        public static readonly Luban.EditorEnumItemInfo Equipment = new Luban.EditorEnumItemInfo("Equipment", "装备", 1, "装备");
        public static readonly Luban.EditorEnumItemInfo Sword = new Luban.EditorEnumItemInfo("Sword", "剑", 2, "剑");
        public static readonly Luban.EditorEnumItemInfo Gun = new Luban.EditorEnumItemInfo("Gun", "枪械", 3, "枪械");
        public static readonly Luban.EditorEnumItemInfo Armor = new Luban.EditorEnumItemInfo("Armor", "护甲", 4, "护甲");
        public static readonly Luban.EditorEnumItemInfo Shoes = new Luban.EditorEnumItemInfo("Shoes", "鞋子", 5, "鞋子");
        public static readonly Luban.EditorEnumItemInfo Helmet = new Luban.EditorEnumItemInfo("Helmet", "头盔", 6, "头盔");
        public static readonly Luban.EditorEnumItemInfo Jewelry = new Luban.EditorEnumItemInfo("Jewelry", "饰品", 7, "饰品");
        public static readonly Luban.EditorEnumItemInfo Consumable = new Luban.EditorEnumItemInfo("Consumable", "消耗品", 8, "消耗品");
        public static readonly Luban.EditorEnumItemInfo Potion = new Luban.EditorEnumItemInfo("Potion", "药水", 9, "药水");
        public static readonly Luban.EditorEnumItemInfo CharaSkill = new Luban.EditorEnumItemInfo("CharaSkill", "人物技能", 10, "人物技能");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            NoType,
            Equipment,
            Sword,
            Gun,
            Armor,
            Shoes,
            Helmet,
            Jewelry,
            Consumable,
            Potion,
            CharaSkill,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

