
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model
{
    /// <summary>
    /// 物品基础类型
    /// </summary>
    public enum ItemBasicType
    {
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 0,
        /// <summary>
        /// 技能
        /// </summary>
        skill = 1,
    }

    public enum ItemBasicType_Alias
    {
        装备 = 0,
        技能 = 1,
    }

    public static class ItemBasicType_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Equipment = new Luban.EditorEnumItemInfo("Equipment", "装备", 0, "装备");
        public static readonly Luban.EditorEnumItemInfo skill = new Luban.EditorEnumItemInfo("skill", "技能", 1, "技能");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Equipment,
            skill,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

