
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GameEditor.ConfigEditor.Model
{
    /// <summary>
    /// 数值类型
    /// </summary>
    public enum NumericId
    {
        /// <summary>
        /// 攻击增伤加值
        /// </summary>
        ATK_INC_DMG_ADD = 1001,
        /// <summary>
        /// 受击减伤加值
        /// </summary>
        DEF_RED_DMG_ADD = 1002,
        /// <summary>
        /// 攻击增伤乘值
        /// </summary>
        ATK_INC_DMG_MUL = 1003,
        /// <summary>
        /// 受击减伤乘值
        /// </summary>
        DEF_RED_DMG_MUL = 1004,
    }

    public enum NumericId_Alias
    {
        攻击增伤加值 = 1001,
        受击减伤加值 = 1002,
        攻击增伤乘值 = 1003,
        受击减伤乘值 = 1004,
    }

    public static class NumericId_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo ATK_INC_DMG_ADD = new Luban.EditorEnumItemInfo("ATK_INC_DMG_ADD", "攻击增伤加值", 1001, "攻击增伤加值");
        public static readonly Luban.EditorEnumItemInfo DEF_RED_DMG_ADD = new Luban.EditorEnumItemInfo("DEF_RED_DMG_ADD", "受击减伤加值", 1002, "受击减伤加值");
        public static readonly Luban.EditorEnumItemInfo ATK_INC_DMG_MUL = new Luban.EditorEnumItemInfo("ATK_INC_DMG_MUL", "攻击增伤乘值", 1003, "攻击增伤乘值");
        public static readonly Luban.EditorEnumItemInfo DEF_RED_DMG_MUL = new Luban.EditorEnumItemInfo("DEF_RED_DMG_MUL", "受击减伤乘值", 1004, "受击减伤乘值");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            ATK_INC_DMG_ADD,
            DEF_RED_DMG_ADD,
            ATK_INC_DMG_MUL,
            DEF_RED_DMG_MUL,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

