
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Cfg.Battle
{ 
    /// <summary>
    /// 命途
    /// </summary>
    public enum Path
    {
        /// <summary>
        /// 丰饶
        /// </summary>
        Abundance = 0,
        /// <summary>
        /// 毁灭
        /// </summary>
        Destruction = 1,
        /// <summary>
        /// 巡猎
        /// </summary>
        TheHunt = 2,
        /// <summary>
        /// 智识
        /// </summary>
        Erudition = 3,
        /// <summary>
        /// 同谐
        /// </summary>
        Harmony = 4,
        /// <summary>
        /// 虚无
        /// </summary>
        Nihility = 5,
        /// <summary>
        /// 存护
        /// </summary>
        Preservation = 6,
    }

} 

