
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace GameEditor.ConfigEditor.Model.Drop
{

public sealed class DropElement :  Luban.EditorBeanBase 
{
    public DropElement()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["drop_item"];
            if (_fieldJson != null)
            {
                
                if (!_fieldJson.IsObject)
                {
                    throw new SerializationException();
                }
                dropItem = GameEditor.ConfigEditor.Model.Drop.Result.DropResult.LoadJsonDropResult(_fieldJson);
            }
            else
            {
                dropItem = Drop.Result.DropResult.Create("DropConfigResult");
            }
        }
        
        { 
            var _fieldJson = _json["factor"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  factor = _fieldJson;
            }
            else
            {
                factor = 0;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {

        if (dropItem != null)
        {
            { var __bjson = new JSONObject();  GameEditor.ConfigEditor.Model.Drop.Result.DropResult.SaveJsonDropResult(dropItem, __bjson); _json["drop_item"] = __bjson; }
        }
        {
            _json["factor"] = new JSONNumber(factor);
        }
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderDropElement(DropElement obj)
    {
        obj.Render();
    }

    public override void Render()
    {
{
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("drop_item", "drop_item"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("drop_item", ""), GUILayout.Width(100));
}
{
    if (this.dropItem == null)
{   
    this.dropItem = Drop.Result.DropResult.Create("DropConfigResult");
}
    Drop.Result.DropResult.RenderDropResult(ref this.dropItem);
}
UnityEditor.EditorGUILayout.EndHorizontal();UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("factor", "factor"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("factor", ""), GUILayout.Width(100));
}
this.factor = UnityEditor.EditorGUILayout.IntField(this.factor, GUILayout.Width(150));
UnityEditor.EditorGUILayout.EndHorizontal();    UnityEditor.EditorGUILayout.EndVertical();
}    }
    public static DropElement LoadJsonDropElement(SimpleJSON.JSONNode _json)
    {
        DropElement obj = new Drop.DropElement();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDropElement(DropElement _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public GameEditor.ConfigEditor.Model.Drop.Result.DropResult dropItem;
    public int factor;

    public override string ToString()
    {
        return "{ "
        + "dropItem:" + dropItem + ","
        + "factor:" + factor + ","
        + "}";
    }
}

}

