
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace GameEditor.ConfigEditor.Model.DicePoolModifier
{

public sealed class CommonModifier :  DicePoolModifier.DicePoolModifierParam 
{
    public CommonModifier()
    {
            skillActiveType = GameEditor.ConfigEditor.Model.SkillActiveType.Attack;
            extraDicePool = GameEditor.ConfigEditor.Model.DicePoolType.Extra;
    }
    public override string GetTypeStr() => TYPE_STR;
    private const string TYPE_STR = "CommonModifier";

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["skill_active_type"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { skillActiveType = (GameEditor.ConfigEditor.Model.SkillActiveType)System.Enum.Parse(typeof(GameEditor.ConfigEditor.Model.SkillActiveType), _fieldJson); } else if(_fieldJson.IsNumber) { skillActiveType = (GameEditor.ConfigEditor.Model.SkillActiveType)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
            else
            {
                skillActiveType = GameEditor.ConfigEditor.Model.SkillActiveType.Attack;
            }
        }
        
        { 
            var _fieldJson = _json["extra_dice_pool"];
            if (_fieldJson != null)
            {
                if(_fieldJson.IsString) { extraDicePool = (GameEditor.ConfigEditor.Model.DicePoolType)System.Enum.Parse(typeof(GameEditor.ConfigEditor.Model.DicePoolType), _fieldJson); } else if(_fieldJson.IsNumber) { extraDicePool = (GameEditor.ConfigEditor.Model.DicePoolType)(int)_fieldJson; } else { throw new SerializationException(); }  
            }
            else
            {
                extraDicePool = GameEditor.ConfigEditor.Model.DicePoolType.Extra;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["skill_active_type"] = new JSONNumber((int)skillActiveType);
        }
        {
            _json["extra_dice_pool"] = new JSONNumber((int)extraDicePool);
        }
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderCommonModifier(CommonModifier obj)
    {
        obj.Render();
    }

    public override void Render()
    {
{
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("技能类型", "skill_active_type"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("skill_active_type", "技能类型"), GUILayout.Width(100));
}
{
    if (ConfigEditorSettings.showComment)
    {
        var __index1 = (int)this.skillActiveType;
        var __alias1 = (SkillActiveType_Alias)this.skillActiveType;
        __alias1 = (SkillActiveType_Alias)UnityEditor.EditorGUILayout.EnumPopup(__alias1, GUILayout.Width(150));
        var __item1 = SkillActiveType_Metadata.GetByNameOrAlias(__alias1.ToString());
        this.skillActiveType = (GameEditor.ConfigEditor.Model.SkillActiveType)__item1.Value;
    }
    else
    {
        this.skillActiveType = (GameEditor.ConfigEditor.Model.SkillActiveType)UnityEditor.EditorGUILayout.EnumPopup(this.skillActiveType, GUILayout.Width(150));
    }
}
UnityEditor.EditorGUILayout.EndHorizontal();UnityEditor.EditorGUILayout.BeginHorizontal();
if (ConfigEditorSettings.showComment)
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("追加骰子池", "extra_dice_pool"), GUILayout.Width(100));
}
else
{
    UnityEditor.EditorGUILayout.LabelField(new UnityEngine.GUIContent("extra_dice_pool", "追加骰子池"), GUILayout.Width(100));
}
{
    if (ConfigEditorSettings.showComment)
    {
        var __index1 = (int)this.extraDicePool;
        var __alias1 = (DicePoolType_Alias)this.extraDicePool;
        __alias1 = (DicePoolType_Alias)UnityEditor.EditorGUILayout.EnumPopup(__alias1, GUILayout.Width(150));
        var __item1 = DicePoolType_Metadata.GetByNameOrAlias(__alias1.ToString());
        this.extraDicePool = (GameEditor.ConfigEditor.Model.DicePoolType)__item1.Value;
    }
    else
    {
        this.extraDicePool = (GameEditor.ConfigEditor.Model.DicePoolType)UnityEditor.EditorGUILayout.EnumPopup(this.extraDicePool, GUILayout.Width(150));
    }
}
UnityEditor.EditorGUILayout.EndHorizontal();    UnityEditor.EditorGUILayout.EndVertical();
}    }
    public static CommonModifier LoadJsonCommonModifier(SimpleJSON.JSONNode _json)
    {
        CommonModifier obj = new DicePoolModifier.CommonModifier();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonCommonModifier(CommonModifier _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// 技能类型
    /// </summary>
    public GameEditor.ConfigEditor.Model.SkillActiveType skillActiveType;
    /// <summary>
    /// 追加骰子池
    /// </summary>
    public GameEditor.ConfigEditor.Model.DicePoolType extraDicePool;

    public override string ToString()
    {
        return "{ "
        + "skillActiveType:" + skillActiveType + ","
        + "extraDicePool:" + extraDicePool + ","
        + "}";
    }
}

}

