
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum NumericValueType
    {
        /// <summary>
        /// B
        /// </summary>
        Base = 0,
        /// <summary>
        /// BA
        /// </summary>
        BaseAdd = 1,
        /// <summary>
        /// BM
        /// </summary>
        BaseMul = 2,
        /// <summary>
        /// FA
        /// </summary>
        FinalAdd = 3,
        /// <summary>
        /// FM
        /// </summary>
        FinalMul = 4,
    }

} 

