
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Unit
{
public partial class TbUnitData
{
    private readonly System.Collections.Generic.Dictionary<int, UnitData> _dataMap;
    private readonly System.Collections.Generic.List<UnitData> _dataList;
    
    public TbUnitData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UnitData>();
        _dataList = new System.Collections.Generic.List<UnitData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UnitData _v;
            _v = UnitData.DeserializeUnitData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UnitData> DataMap => _dataMap;
    public System.Collections.Generic.List<UnitData> DataList => _dataList;

    public UnitData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UnitData Get(int key) => _dataMap[key];
    public UnitData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

